appname: bdev
httpport: 5008
runmode: prod
autorender: false
copyrequestbody: true
grpclisten: :5008
pgdatasource: user=postgres password=postgres dbname=test host=127.0.0.1 port=5432 sslmode=disable
ormdebug: true
enabledocs: true
loglevel: 7
jwt_salt: testsalt
redisconf:
  address: 127.0.0.1:6379
  auth: ""
  name: redis
  type: tcp
  db: "2"
mysqlconf:
  allconfig: root:@tcp(localhost:3306)/mydb
  host: "3306"
  mysql: mysql
  name: root
  password: ""
  type: tcp
